#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Very basic tool to generate a binary map of a background from a
# 128 x 128 picture. It allows detecting if an explosion occured
# on Conan The Simpsonian, or not ;p
#

import sys
import Image

IMAGE = sys.argv[1]
background = (255,255,255,255) # white

print """/*
 * 128x128 binary map of image background.
 * AUTOMATICALLY GENERATED by %s from %s
 */

static const uint8_t bin_map[] = { """ % (sys.argv[0], IMAGE)

im = Image.open(IMAGE)
width, height = im.size
pix = im.load()

for y in range(height):
    bytes = []
    byte = 0
    for x in range(width):
        if x != 0 and x % 8 == 0:
            bytes.append(byte)
            byte = 0
        if pix[x,y] != background:
            byte = byte | (1 << x%8)
    bytes.append(byte)
    print "    %s" % "".join(["0x%02x," % x for x in bytes])

print "};"

